image: node:latest

services:
  - mongo:latest

cache:
  paths:
  - views/
  - public/
  - node_modules/

stages:
   - build
   - lint
   - test

build:
  script:
   - npm install
  stage: build

lint:
  script:
   - npm run lint
  stage: lint

test:
  script:
   - npm test
  stage: test
