services:
  - mongo:latest

cache:
  paths:
  - views/
  - public/
  - node_modules/

before_script:
  - apt-get update -yq

stages:
   - lint
   - test
   - deploy

lint:
  image: node:latest
  script:
   - yarn
   - yarn lint
  stage: lint

test:
  image: node:latest
  script:
   - yarn
   - yarn test
  stage: test

staging:
  image: ruby:latest
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=blog-server-dev --api-key=$HEROKU_STAGING_API_KEY --strategy=git
  only:
    - master

production:
  image: ruby:latest
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=blog-server-prod --api-key=$HEROKU_PRODUCTION_API_KEY --strategy=git
  only:
    - tags
