image: node:latest

services:
  - mongo:latest

cache:
  paths:
  - views/
  - public/
  - node_modules/

variables:
  MONGODB_URI: 'mongodb://mongo/rukeith-blog'

before_script:
  - npm install
  - apt-get update -yq

stages:
   - lint
   - test
   - deploy

lint:
  script:
   - npm run lint
  stage: lint

test:
  script:
   - npm test
  stage: test

staging:
  image: ruby:latest
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=blog-server-dev --api-key=$HEROKU_STAGING_API_KEY
  only:
    - master

production:
  image: ruby:latest
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=blog-server-prod --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
    - tags
