cache:
  paths:
  - views/
  - public/
  - node_modules/

stages:
  - lint
  - test
  - deploy

lint:
  stage: lint
  image: node
  before_script:
    - yarn
  script:
    - yarn lint

test:
  stage: test
  image: node
  services:
    - mongo
    - redis
  before_script:
    - yarn
  script:
    - yarn test

staging:
  stage: deploy
  image: ruby
  only:
    - develop
  environment:
    name: staging
    url: https://blog-server-dev.herokuapp.com
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=blog-server-dev --api-key=$HEROKU_STAGING_API_KEY --strategy=git

production:
  stage: deploy
  image: ruby
  only:
    - tags
  except:
    - branches
  environment:
    name: production
    url: https://blog-server-prod.herokuapp.com
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=blog-server-prod --api-key=$HEROKU_PRODUCTION_API_KEY --strategy=git