image: node:latest

services:
  - mongo:latest

cache:
  paths:
  - views/
  - public/
  - node_modules/

variables:
  MONGODB_URI: 'mongodb://mongo/rukeith-blog'

before_script:
  - npm install

stages:
   - lint
   - test

lint:
  script:
   - npm run lint
  stage: lint

test:
  script:
   - npm test
  stage: test
