image: node:latest

services:
  - mongo:latest

cache:
  paths:
  - views/
  - public/
  - node_modules/

variables:
  MONGODB_URI: 'mongodb://mongo/rukeith-blog'

before_script:
  - npm install
  - apt-get update -yq
  - apt-get install -y ruby-dev
  - ruby -v
  - gem install dpl

stages:
   - lint
   - test
   - deploy

lint:
  script:
   - npm run lint
  stage: lint

test:
  script:
   - npm test
  stage: test

staging:
  stage: deploy
  script:
  - dpl --provider=heroku --app=blog-server-dev --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master

production:
  stage: deploy
  script:
  - dpl --provider=heroku --app=blog-server-prod --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - tags
