version: "3.5"
services:
  mongo:
    image: mongo
    container_name: blog-database
    restart: on-failure:5
    labels:
      - "CI-TEST=jenkins"
    networks:
      - blog-network

  server:
    build: ./
    image: backend
    container_name: blog-server
    labels:
      - "CI-TEST=jenkins"
    networks:
      - blog-network
    depends_on:
      - mongo

networks:
  blog-network:
    labels:
      - "CI-TEST=jenkins"
    name: blog-network