version: "3"
services:
  mongo:
    image: mongo
    container_name: blog-server-mongo
    restart: on-failure:5
    labels:
      - "CI-TEST=jenkins"
    networks:
      - backend

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: backend
    container_name: blog-server-backend
    labels:
      - "CI-TEST=jenkins"
    networks:
      - backend
    depends_on:
      - mongo

networks:
  backend:
    labels:
      - "CI-TEST=jenkins"