version: "3.7"

services:
  mongo:
    image: mongo
    container_name: blog-mongo
    labels:
      - "PROJECT=blog"
      - "SERVICE=mongo"
    networks:
      - blog-network
    ports: 
      - "27017:27017"

  redis:
    image: redis
    container_name: blog-redis
    labels:
      - "PROJECT=blog"
      - "SERVICE=redis"
    networks:
      - blog-network
    ports: 
      - "6379:6379"

  server:
    build:
      context: .
      labels:
        - "PROJECT=blog"
        - "SERVICE=server"
    image: backend
    container_name: blog-server
    labels:
      - "PROJECT=blog"
      - "SERVICE=server"
    networks:
      - blog-network
    environment:
      - PORT=443
      - NODE_ENV=production
      - MONGODB_URI=mongodb://blog-mongo:27017/rukeith-blog
      - REDIS_URL=redis://blog-redis:6379
      - USERNAME=rukeith
      - PASSWORD=iampassword
      - SALT=iamsalt
      - HASH_PASSWORD=22e9092cea7d4425fa818ffd8c7309e5d1b7df456a74221d7ff9530897ada514f53b621a182d909cb7171d420fac990ef7ac4dc3a1a58cf672e03849c61d0e73
      - JWT_SECRET=blog
      - ISSUER=rukeith
    depends_on:
      - mongo
      - redis
    ports: 
      - "443:443"

networks:
  blog-network:
    name: blog-network
    labels:
      - "PROJECT=blog"
      - "SERVICE=network"