version: "3.5"
services:
  mongo:
    image: mongo
    container_name: blog-mongo
    labels:
      - "CI-TEST=jenkins"
      - "PLATFORM=blog"
    networks:
      - blog-network

  redis:
    image: redis
    container_name: blog-redis
    labels:
      - "CT-TEST=jenkins"
    networks:
      - blog-network

  server:
    build: ./
    image: backend
    container_name: blog-server
    labels:
      - "CI-TEST=jenkins"
      - "PLATFORM=blog"
    networks:
      - blog-network
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://blog-mongo:27017/rukeith-blog
      - REDIS_URL=redis://blog-redis:6379
      - USERNAME=rukeith
      - PASSWORD=iampassword
      - SALT=iamsalt
      - HASH_PASSWORD=418b24c67f21cb9da47b3732a59a207e62cb9a58d368166c5c99f5dbddc6ac9c7257ad513984c733ca1f3e1718798dab066ba3965fee15429f4a4391f586d15d
      - JWT_SECRET=blog
    depends_on:
      - mongo
      - redis

networks:
  blog-network:
    labels:
      - "CI-TEST=jenkins"
      - "PLATFORM=blog"
    name: blog-network
